name: install protoc

runs:
  using: "composite"
  steps:
    - name: get latest protoc version
      shell: bash
      id: protoc-version
      run: >
        version=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/protocolbuffers/protobuf/releases/latest | jq -r '.tag_name | sub("^v"; "")')

        echo "protoc-version=$version" >> $GITHUB_OUTPUT
    - uses: arduino/setup-protoc@v3
      with:
        version: ${{ steps.protoc-version.outputs.protoc-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
