name: publish vuepress page

inputs:
  cmd:
    description: The pnpm command used to build the VuePress site
    required: false
    default: docs:build
  build_path:
    description: The path to the directory that contains statically generated files.
    required: false
    default: docs/.vuepress/dist/
  working_directory:
    description: The working directory to run the build from.
    required: false
    default: ./

outputs:
  page_url:
    description: The URL where the github page is published
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        # fetch all commits to get last updated time or other git log info
        fetch-depth: 0
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
        package_json_file: ${{ inputs.working_directory }}/package.json
    - uses: actions/setup-node@v5
      with:
        node-version: latest
        cache: pnpm
        cache-dependency-path: ${{ inputs.working_directory }}/pnpm-lock.yaml
    - name: install deps
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm install --frozen-lockfile
    # run build script
    - name: build VuePress site
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: pnpm ${{ inputs.cmd }}
    - uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ inputs.build_path }}
    - uses: actions/configure-pages@v5
    - id: deployment
      uses: actions/deploy-pages@v4
