name: lint node

inputs:
  lint_action:
    required: false
    description: The name of the lint command in the package file.
    default: lint
  github_token:
    required: true
    description: The GitHub token to use for the action.
  app_private_key:
    required: true
    description: The Github App private key.
  app_id:
    required: true
    description: The Github App ID.

runs:
  using: "composite"
  steps:
    - uses: a-novel-kit/workflows/node-actions/setup-node@master
      id: app_token
      with:
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}
        github_token: ${{ inputs.github_token }}
    - name: run lint
      shell: bash
      run: pnpm run ${{ inputs.lint_action }}
