name: lint node

inputs:
  lint_action:
    required: false
    description: The name of the lint command in the package file.
    default: lint
  pat:
    required: true
    description: The personal access token to use for the action.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: setup github registry
      shell: bash
      run: |
        pnpm config set "@a-novel:registry" "https://npm.pkg.github.com"
        pnpm config set "//npm.pkg.github.com/:_authToken" "${{ inputs.pat }}"
    - name: install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
    - name: run lint
      shell: bash
      run: pnpm run ${{ inputs.lint_action }}
