name: test node
description: Set up Node, run the package's test script, and upload the coverage report.

inputs:
  test_action:
    required: false
    description: The name of the test command in the package file.
    default: test
  github_token:
    required: true
    description: The GitHub token to use for the action.
  app_private_key:
    required: true
    description: The GitHub App private key.
  client_id:
    required: false
    description: GitHub App client id (recommended).
  coverage_artifact:
    required: false
    description: The name of the artifact to store the coverage report.
    default: coverage
  coverage_file:
    required: false
    description: The name of the coverage report file.
    default: coverage/*

outputs:
  artifact-id:
    description: The coverage artifact id.
    value: ${{ steps.upload-artifact.outputs.artifact-id }}

runs:
  using: "composite"
  steps:
    - uses: a-novel-kit/workflows/node-actions/setup-node@v1.26.0
      id: app_token
      with:
        client_id: ${{ inputs.client_id }}
        app_private_key: ${{ inputs.app_private_key }}
        github_token: ${{ inputs.github_token }}
    - name: run test
      shell: bash
      run: pnpm run ${{ inputs.test_action }}
    - name: archive code coverage results
      id: upload-artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.coverage_artifact }}
        path: ${{ inputs.coverage_file }}
