name: test go

inputs:
  test_args:
    required: false
    description: The arguments to pass to the test command.
    default: -p 1 -race
  test_artifact:
    required: false
    description: The name of the artifact to store the test report.
    default: go-test
  coverage_artifact:
    required: false
    description: The name of the artifact to store the coverage report.
    default: coverage
  test_file:
    required: false
    description: The name of the test report file.
    default: tests.json
  coverage_file:
    required: false
    description: The name of the coverage report file.
    default: coverage.txt
  skip_setup:
    required: false
    description: Skip the setup steps.
  filter_patterns:
    required: false
    description: The file patterns to filter.
    default: "| grep -v /mocks | grep -v /test | grep -v /proto"
  filter_extra_patterns:
    required: false
    description: The file patterns to filter, appended to filter_patterns.
    default: ""

outputs:
  artifact-id:
    description: The coverage artifact id.
    value: ${{ steps.upload-artifact.outputs.artifact-id }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      if: ${{ inputs.skip_setup != 'true' }}
    - uses: actions/setup-go@v6
      if: ${{ inputs.skip_setup != 'true' }}
      with:
        go-version-file: "go.mod"
    - name: download go packages
      if: ${{ inputs.skip_setup != 'true' }}
      shell: bash
      run: go mod download
    - name: discover modules
      shell: bash
      id: discover
      run: |
        # List all modules using `go list -m`, and for each module, list every package.
        # The extra `go list -m` steps is used to discover multiple modules when working with workspaces.
        echo "$(for mod in $(go list -m); do go list ${mod//$(go list .)/.}/... ${{ inputs.filter_patterns }} ${{ inputs.filter_extra_patterns }}; done)" > modules.txt
        echo "MODULES=$(cat modules.txt | tr '\n' ' ')" >> $GITHUB_ENV
    - name: run tests
      shell: bash
      run: |
        go tool gotestsum --jsonfile ${{ inputs.test_file }} --format pkgname \
          -- -count=1 -cover -coverprofile=${{ inputs.coverage_file }} -json ${{ env.MODULES }}

        go tool cover -func ${{ inputs.coverage_file }}
    - name: archive code coverage results
      id: upload-artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.coverage_artifact }}
        path: ${{ inputs.coverage_file }}
    - name: archive test results
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.test_artifact }}
        path: ${{ inputs.test_file }}
