name: approve bot
description: Records a pull request approval on every invocation. Only enable this for a specific set of users.

inputs:
  pull_request:
    required: true
    description: The URL of the pull request to be approved.
  github_token:
    required: true
    description: The GitHub token to use for the action.

runs:
  using: "composite"
  steps:
    - name: approve PR
      shell: bash
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ inputs.pull_request }}
        GH_TOKEN: ${{ inputs.github_token }}
