name: Codecov Go

inputs:
  coverage_artifact:
    required: false
    description: The name of the artifact to store the coverage report.
    default: go-coverage
  coverage_file:
    required: false
    description: The name of the coverage report file.
    default: coverage.txt
  codecov_token:
    required: true
    description: The codecov token used to upload coverage reports

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.coverage_artifact }}
      # If using a different file name as an input, rename it so it is recognized by the codecov-action.
    - name: Normalize file name
      shell: bash
      if: ${{ inputs.coverage_file != 'coverage.txt' }}
      run: |
          mv ${{ inputs.coverage_file }} coverage.txt
    - uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ inputs.codecov_token }}
      with:
        fail_ci_if_error: true
