name: auto-merge bot
description: Activate auto-merge for a pull request.

inputs:
  pull_request:
    required: true
    description: The URL of the pull request to be merged.
  github_token:
    required: true
    description: The GitHub token to use for the action.

runs:
  using: "composite"
  steps:
    - name: fetch metadata
      id: metadata
      uses: dependabot/fetch-metadata@e74077de530ef48d09568e2268558f6093a85509
      with:
        github-token: "${{ inputs.github_token }}"
    - name: enable auto-merge
      shell: bash
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ inputs.pull_request }}
        GH_TOKEN: ${{ inputs.github_token }}
