name: publish npm

inputs:
  build_action:
    required: false
    description: The name of the build command in the package file.
    default: build
  github_token:
    required: true
    description: The GitHub token to use for the action.
  app_private_key:
    required: true
    description: The Github App private key.
  app_id:
    required: true
    description: The Github App ID.

runs:
  using: "composite"
  steps:
    - uses: a-novel-kit/workflows/node-actions/setup-node@master
      id: app_token
      with:
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}
        github_token: ${{ inputs.github_token }}
    - name: build
      shell: bash
      run: pnpm run ${{ inputs.build_action }}
    - run: pnpm publish -r --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github_token }}
