name: setup node

inputs:
  github_token:
    required: true
    description: The GitHub token to use for the action.
  app_private_key:
    required: true
    description: The Github App private key.
  app_id:
    required: true
    description: The Github App ID.

outputs:
  token:
    description: The bot token.
    value: ${{ steps.app_token.outputs.token }}
  app_login:
    description: The login name of the bot.
    value: ${{ steps.app_token.outputs.app_login }}

runs:
  using: "composite"
  steps:
    - uses: a-novel-kit/workflows/generic-actions/pull-bot@master
      id: app_token
      with:
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        package-manager-cache: false
        node-version: "lts/*"
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
    - name: setup github registry
      shell: bash
      run: |
        pnpm config set "@a-novel:registry" "https://npm.pkg.github.com"
        pnpm config set "@a-novel-kit:registry" "https://npm.pkg.github.com"
        pnpm config set "//npm.pkg.github.com/:_authToken" "${{ inputs.github_token }}"
    - name: install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
