name: assign bot
description: Automatically assigns the author of a pull request to the PR.

inputs:
  github_token:
    required: true
    description: The GitHub token to use for the action.

runs:
  using: "composite"
  steps:
    - name: assign author
      shell: bash
      run: |
        echo "Assigning author to PR"
        echo "PR author: ${{ github.event.pull_request.user.login }}"
        echo "PR number: ${{ github.event.pull_request.number }}"
        echo "Assigning author to PR"
        gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
          -f "assignees[]=${{ github.event.pull_request.user.login }}"
      env:
        GH_TOKEN: ${{ inputs.github_token }}
