name: build node
description: Set up Node and run the package's build script.

inputs:
  build_action:
    required: false
    description: The name of the build command in the package file.
    default: build
  github_token:
    required: true
    description: The GitHub token to use for the action.
  app_private_key:
    required: true
    description: The GitHub App private key.
  client_id:
    required: false
    description: GitHub App client id (recommended).

runs:
  using: "composite"
  steps:
    - uses: a-novel-kit/workflows/node-actions/setup-node@v1.15.7
      id: app_token
      with:
        client_id: ${{ inputs.client_id }}
        app_private_key: ${{ inputs.app_private_key }}
        github_token: ${{ inputs.github_token }}
    - name: build
      shell: bash
      run: pnpm run ${{ inputs.build_action }}
