name: codecov
description: Uploads code coverage reports to Codecov.

inputs:
  coverage_artifact:
    required: false
    description: The name of the artifact to store the coverage report.
  coverage_artifact_ids:
    required: false
    description: The ids of the coverage report file.
  coverage_files:
    required: false
    description: The name of the coverage report file.
  codecov_token:
    required: true
    description: The codecov token used to upload coverage reports

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.coverage_artifact }}
        artifact-ids: ${{ inputs.coverage_artifact_ids }}
    - uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ inputs.codecov_token }}
      with:
        fail_ci_if_error: true
        files: ${{ inputs.coverage_files }}
