name: compose service
description: Run a compose file, and make sure it reports healthy when run.

inputs:
  file:
    required: true
    description: Path of the compose, relative to repository root.
  github_token:
    required: true
    description: The GitHub token to use for publication.
  project:
    required: true
    description: The docker compose project name.

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - uses: docker/setup-qemu-action@v3
    - name: run containers
      shell: bash
      run: |
        docker compose -f "${{ inputs.file }}" -p ${{ inputs.project }} up -d --wait
