name: auto-merge

inputs:
  pull_request:
    required: true
    description: The URL of the pull request to be merged.
  pat:
    required: true
    description: The personal access token to use for the action.
  github_token:
    required: true
    description: The GitHub token to use for the action.

runs:
  using: "composite"
  steps:
    - name: Auto approve PR
      shell: bash
      run: |
        gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
        if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
        then gh pr review --approve "$PR_URL"
        else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
        fi
      env:
        PR_URL: ${{ inputs.pull_request }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Enable auto-merge
      shell: bash
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ inputs.pull_request }}
        GH_TOKEN: ${{ inputs.pat }}
