name: OpenAPI CI

on:
  workflow_call:

jobs:
  lint-redocly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Run linting
        run: redocly lint docs/api.yaml --format=github-actions
