name: run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./generic-actions/renovate
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          app_id: ${{ vars.DEPENDENCY_BOT_ID }}
