name: Build Docker API

inputs:
  file:
    required: false
    description: Path of the dockerfile, relative to repository root.
    default: "Dockerfile"
  image_name:
    required: true
    description: The name of the image to build.
  run_args:
    required: false
    description: Args to use for the test run of the image.
  timeout:
    required: false
    description: Timeout (in deciseconds) for the container healthcheck.
    default: "300"
  tcp_timeout:
    required: false
    description: Timeout (in deciseconds) for the tcp healthcheck.
    default: "600"
  ping:
    required: false
    description: The ping endpoint.
    default: /v1/ping
  skip_healthcheck:
    required: false
    description: Skip the test run of the image.
  github_token:
    required: true
    description: The GitHub token to use for publication.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ inputs.image_name }}
        tags: |
          # Default tags
          type=ref,event=pr
          type=ref,event=branch
          type=ref,event=tag
          # Versioning tags
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
        flavor: latest=auto
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - uses: docker/setup-buildx-action@v3
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: ghcr.io/${{ inputs.image_name }}:test
        file: ${{ inputs.file }}
    - name: Install check tools
      shell: bash
      run: sudo apt install curl
    - name: Test docker image
      id: local_container
      shell: bash
      if: ${{ inputs.skip_healthcheck != 'true' }}
      run: |
        docker run -d --network="host" -p 8080:8080 -e PORT=8080 ${{ inputs.run_args }} --name test-container \
            ghcr.io/${{ inputs.image_name }}:test

        until [ "`docker inspect --type=container -f {{.State.Running}} test-container`" == "true" ]
        do 
          ((c++)) && ((c==${{ inputs.timeout }})) && break
          sleep 0.1
        done

        if [ "`docker inspect -f {{.State.Running}} test-container`" == "true" ]
        then
          echo "Container started successfuly"
          exit 0
        else
          echo "Container failed to report ready status"
          docker stop test-container
          echo "Extracting logs"
          docker logs test-container
          exit 1
        fi
    - name: TCP check
      if: ${{ success() && inputs.skip_healthcheck != 'true' }}
      shell: bash
      run: |
        while ! curl -s 127.0.0.1:8080${{ inputs.ping }}
        do 
          ((c++)) && ((c==${{ inputs.tcp_timeout }})) && break
          sleep 0.1
        done
        curl 127.0.0.1:8080${{ inputs.ping }} || (docker stop test-container && docker logs test-container && exit 1)
        docker stop test-container
    - uses: docker/build-push-action@v6
      if: ${{ success() }}
      id: build
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.file }}
